### PR TITLE
Fix missing prebid.targeting

### PR DESCRIPTION
**Pull request by AntoineJac**

### CODE REVIEW

**Comment by AntoineJac** [comment]
"request.ext.prebid.targeting" must be present event is the value is void {}. Or Prebid Server won't set the KV on the response at response.seatbid[i].bid[j].ext.prebid.targeting

**Comment by AntoineJac** [comment]
@ppuviarasu  and @anwzhang , please review

**Comment by anwzhang** [comment]
Hi @AntoineJac ,

I approved this, does iOS need same work too?

**Comment by AntoineJac** [comment]
Hi @anwzhang , thanks a lot. 
iOS should be fine as you have implemented this change in:
https://github.com/prebid/prebid-mobile-ios/pull/90/files

**Pull request merged**
