### PR TITLE
1.1.1 findPrebidCreativeSize function does not work with Compile error

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub issue #116

### CODE REVIEW

**Comment by anwzhang** [comment]
Hi, @yoalex5 

Do I need to rebuild the product or just merge this? Should we update the documentation?

**Comment by yoalex5** [comment]
Hello, @anwzhang 

>Do I need to rebuild the product or just merge this? 
@bszekely1, what do you think ? 
From my perspective, it would be great to rebuild the Maven release and GitHub release v1.1.1 with this commit. 

>Should we update the documentation?
We do not need to update the doc

**Comment by bszekely1** [comment]
Lets rebuild under the 1.1.1 tag. No need to increment the version. This release is to have a working 1.1.1 version.

**Comment by ptomasroos** [comment]
Great. This most likely solves the case that we can't set Gender on TargetingParams either. Same error, nested enum's are not exposed or "stripped"

Screenshot 2019-07-03 at 17 14 27

**Comment by yoalex5** [comment]
@ptomasroos, thanks that you pointed it out. I have updated proguard rules

**Comment by ptomasroos** [comment]
Thanks @yoalex5 

Your commit should also solve #121 in that case

**Comment by ptomasroos** [comment]
Looking fwd to a merge and release of this!

**Pull request merged**
