### PR TITLE
Add option to set prebid server host url 

### PR DESCRIPTION
**Pull request by randeepsiddhu**

### CODE REVIEW

**Comment by anwzhang** [comment]
Approved, wait until Integration tests fixed to be merged.

**Comment by anwzhang** [comment]
@randeepsiddhu Can you rebase from master to make sure that the tests are passing before I merge this branch?

**Comment by randeepsiddhu** [comment]
@anwzhang All the unit tests are passing except one of the calabash test
 Pbm.js not found, prebid creative was not served (RuntimeError)
      ./features/step_definitions/calabash_steps.rb:10:in `/^I should see AppNexus creative$/'

**Comment by anwzhang** [comment]
@randeepsiddhu do you have a link to the test?

**Comment by randeepsiddhu** [comment]
I ran prebid-mobile-android-fork/PrebidMobile/IntegrationTests/run_tests_local.sh locally.
BUILD SUCCESSFUL

Total time: 1 mins 22.414 secs
CALABASH BUILDLOG: Run the tests.
No test server found for this combination of app and calabash version. Recreating test server.
Done signing the test server. Moved it to test_servers/87942df1597a968a7c729f96c7776229_0.9.0.apk
Feature: Base test

  Scenario: Load DFP Banner Ad                           # features/base_test.feature:3
    Given I wait for the "MainActivity" screen to appear # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:51
    Then I press "DFP"                                   # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I press "Show Banner Example"                   # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I press "Refresh Banner"                        # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I wait for 10 seconds                           # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:10
    Then I should see AppNexus creative                  # features/step_definitions/calabash_steps.rb:3
      Pbm.js not found, prebid creative was not served (RuntimeError)
      ./features/step_definitions/calabash_steps.rb:10:in `/^I should see AppNexus creative$/'
      features/base_test.feature:9:in `Then I should see AppNexus creative'

  #Scenario: Load DFP Interstitial Ad
  #Given I wait for the "MainActivity" screen to appear
  #Then I press "DFP"
  #Then I press "Show Interstitial Example"
  #Then I press "loadInterstitial"
  #Then I wait for 5 seconds
  #Then I should see AppNexus creative
  #Then I press "Interstitial close button"
  Scenario: Load MoPub Banner Ad                             # features/base_test.feature:20
    Given I wait for the "MainActivity" screen to appear     # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:51
    Then I press "MoPub"                                     # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I press "Show Banner Example"                       # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I press "Refresh Banner"                            # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:17
    Then I wait for 10 seconds                               # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:10
    Then I should see AppNexus creative in HTMLBannerWebView # features/step_definitions/calabash_steps.rb:22

Failing Scenarios:
cucumber features/base_test.feature:3 # Scenario: Load DFP Banner Ad

2 scenarios (1 failed, 1 passed)
12 steps (1 failed, 11 passed)
0m54.904s

**Comment by anwzhang** [comment]
@randeepsiddhu does the test always fail or only a few times?

**Comment by randeepsiddhu** [comment]
@anwzhang I just ran the test again and it passed this time!

**Comment by anwzhang** [comment]
@randeepsiddhu I think the tests are unstable. This can be merged. More testing efforts are captured here: https://github.com/prebid/prebid-mobile-android/issues/33

**Pull request merged**
