### PR TITLE
Add a config Class

### PR DESCRIPTION
**Pull request by AntoineJac**
Similar to the setConfig for Prebid.js create a class for current and future feature

### CODE REVIEW

**Comment by AntoineJac** [comment]
@anwzhang here is the last version. By default I have followed your recommandation and it will pass the account for the StoredRequestId without priceGranularity.

The StoredRequestId and the PriceGranularity could be set up by calling the PbConfig class methods.

If all ok can you please merge. Thanks,

**Comment by AntoineJac** [comment]
@ppuviarasu can you please review this PR.

Thanks,

**Comment by mjacobsonny** [comment]
@AntoineJac -- Can I ask that you please open an Intent to Implement issue where we can discuss the API change(s) proposed herein?

In the interim, I am going to close this PR.

**Comment by AntoineJac** [comment]
@mjacobsonny , thanks. I think it was cleaner and better to create a new config class. 
I let you discuss this with other PM. 

Meanwhile Please review the PR to fix the missing request.ext.prebid.targeting 
https://github.com/prebid/prebid-mobile-android/pull/65

**Pull request closed without merging**
