### PR TITLE
Clicktrackers implementation for Native ads

### PR DESCRIPTION
**Pull request by clho40**
Motivation: Feature request #649 

Currently, the Prebid Mobile SDK is not making use of the link.clicktrackers of the standard OpenRTB protocol. This pull request is to implement that feature.

Whenever a native ad is tapped (or, "clicked"), it should send HTTP GET requests to all the urls in the `link.clicktrackers` array.

### CODE REVIEW

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 ! Thanks for the contribution! 

Quick question - are you going to implement `clicktrackers` support on iOS?

**Comment by clho40** [comment]
> Hi @clho40 ! Thanks for the contribution!
> 
> Quick question - are you going to implement `clicktrackers` support on iOS?

Hello @YuriyVelichkoPI ! I wish I could but I have no experience on iOS development 😔

**Comment by clho40** [comment]
on a side note, this pull request seems to have included the other pull request #493 , sorry bout that. How do I remove them from here?

**Comment by YuriyVelichkoPI** [comment]
> > Hi @clho40 ! Thanks for the contribution!
> > Quick question - are you going to implement `clicktrackers` support on iOS?
> 
> Hello @YuriyVelichkoPI ! I wish I could but I have no experience on iOS development 😔

No worries! I just want to understand how to move forward. In this case, I'll create an issue iOS repo for supporting the `clicktrackers` and the committee will decide when and how to assign dev resources for it.

**Comment by YuriyVelichkoPI** [comment]
> on a side note, this pull request seems to have included the other pull request #493 , sorry bout that. How do I remove them from here?

I believe that the best way is to create new separate branches in your repo and redo the PRs so each of them contains relevant changes. 

This one can be just closed.

**Comment by ValentinPostindustria** [comment]
Hi. The changes for click trackers look great. Just leave these 4 files, make rebase onto master and we can merge. Or create a new PR.
Screenshot_20230705_130306

**Pull request closed without merging**
