### PR TITLE
Expose setPrebidUserAaid, getPrebidUserAaid and setPrebidUserAgent

### PR DESCRIPTION
**Pull request by derN3rd**
This PR exposes functions to set the idfa and user agent, as a workaround for https://github.com/prebid/prebid-mobile-android/issues/101

Tested this in our react-native app and the first prebid request therefore has the data, we set before

### CODE REVIEW

**Comment by yoalex5** [comment]
Hello @derN3rd , thanks for your PR. 

As I see you propose just to expose SDK API to define `aaid`, `limitAdTracking`, `userAgent ` for a publisher. I suppose that they were hidden on purpose. 

I think we should come up with an approach to setup these field internally in the SDK.

@ppuviarasu, what do you think ?

**Comment by derN3rd** [comment]
I agree this is only a workaround (or a way, to set these properties if you already have them).

As mentioned in the issue #101 aaid and userAgent get set async, which might be too late for the first requests, which causes no bids on almost every first request made. But with this exposed functions I set them directly on initialization and so the first request has aaid and userAgent.

As far as I see this is caused by https://github.com/prebid/prebid-mobile-android/blob/644b9cfc77314cfd3204cdeb742285087ed2ee37/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdvertisingIDUtil.java#L83-L96 being async and https://github.com/prebid/prebid-mobile-android/blob/644b9cfc77314cfd3204cdeb742285087ed2ee37/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerSettings.java#L80-L91 which also doesn't finish before the first request.

So why not letting the dev set the two values manually if he already has them (in state or something) instead of waiting on their own async tasks and leading to failing ad requests?

**Comment by anwzhang** [comment]
@derN3rd this is resolved by #169 

I'll close this PR once you confirm it.

**Comment by Jobeso** [comment]
We tried out #169 and it works fine so you can close this pr. Thanks for taking care of it.

**Pull request closed without merging**
