### PR TITLE
fix bugs and add feature to select PBS host

### PR DESCRIPTION
**Pull request by littleV**
Bug 1, app was adding data to null adUnit, fix makes sure ad unit is created.
Bug 2, AppNexus PBS hasn't supported 1st party data yet, so the demo is broken
Feature: able to select HOST to demo with on the main activity

### CODE REVIEW

**Comment by anwzhang** [comment]
@yoalex5 I've marked the tests passing or failing, you can use the following command to run just failing tests:
./gradlew connectedSourceCodeDebugAndroidTest -P android.testInstrumentationRunnerArguments.annotation=org.prebid.mobile.app.FailingTest

Please help to resolve Rubicon related tests and the DFPBannerComplexText

**Comment by yoalex5** [comment]
@anwzhang, pr #168 was created

**Comment by yoalex5** [comment]
Hello @anwzhang 

Are we going to merge this PR ?

**Comment by bszekely1** [comment]
@anwzhang Is this pull request still required? We want to clean up open pull requests. RP has fixed outstanding issue as noted above.

**Comment by bszekely1** [comment]
Closing this PR for now. If someone feels this should be released, please take appropriate action to open this back up and we can discuss it on our PMC meeting.

**Pull request closed without merging**
