### PR TITLE
Introduced the possibility to add custom headers to prebid post requests.

### PR DESCRIPTION
**Pull request by gianpiero-bozza**
This change makes it possible to pass custom headers to post requests to prebid.
Two new tests have been added to the suite to cover this behaviour and the production code resided in 2 classes only, PrebidMobile.java and HTTPPost.java

### CODE REVIEW

**Comment by YuriyVelichkoPI** [comment]
Hi @gianpiero-bozza! 

What is the motivation for adding custom headers?

**Comment by gianpiero-bozza** [comment]
> Hi @gianpiero-bozza!
> 
> What is the motivation for adding custom headers?

Hi @YuriyVelichkoPI !
our business dept. requested us a to send a custom header in the PBS requests which would allow them to accomplish several use cases such as:

- Rolling out PBS updates only on selected apps
- Monitoring on SDK and bundle id
- Run tests on selected app and sdk versions

We thought this could be a feature that can be useful for the general public too.

**Comment by YuriyVelichkoPI** [comment]
Is this an original PBS feature or do you have custom logic for PBS? I can't find this in PBS docs.

**Comment by gianpiero-bozza** [comment]
> Is this an original PBS feature or do you have custom logic for PBS? I can't find this in PBS docs.

I don't believe we have custom logic, we just forked your master and added some features, like the contentUrl a few months ago.
As far as docs, I didn't see documentation to be updated in this repo.

**Comment by YuriyVelichkoPI** [comment]
Got it, thanks for the clarification. 

Two additional questions :)
Are you able to make respective changes for iOS? 
How urgent is this feature for you?

**Comment by gianpiero-bozza** [comment]
> Got it, thanks for the clarification.
> 
> Two additional questions :) Are you able to make respective changes for iOS? How urgent is this feature for you?

No problems! Glad we could clarify it :)
it's not super urgent and in the next days the team should prepare the same change for iOS too, so I guess this can be done in parallel for both architectures on your end.

Thank you very much!

**Comment by marcelklinek** [comment]
iOS version of this PR: https://github.com/prebid/prebid-mobile-ios/pull/490

**Review by YuriyVelichkoPI — APPROVED** [review]
LGTM

**Pull request merged**
