### PR TITLE
Adform integration

### PR DESCRIPTION
**Pull request by rprunskas**
Added Adform Advertising SDK integration in PrebidMobileCore and DemoApp.

### CODE REVIEW

**Comment by anwzhang** [comment]
Hi @rprunskas , the code looks good to me. But we don't want to release/merge this until we have proper documentation on prebid.org, e.g. (http://prebid.org/prebid-mobile/prebid-mobile.html)

If you could draft a page on ad ops set up and code integration, we'll review it and release both at the same time. Here's the repo for prebid.org: https://github.com/prebid/prebid.github.io

Let me know if you have any questions or need help there.

**Comment by anwzhang** [comment]
@rprunskas Any updates on the documentation?

**Comment by rprunskas** [comment]
@anwzhang please check [documentation pull request](https://github.com/prebid/prebid.github.io/pull/998), I also removed Adform Interstitial implementation in https://github.com/prebid/prebid-mobile-android/pull/53/commits/c4b9d83a149e75f9d6e062b35b75c783c38bde6a commit.

**Comment by bretg** [comment]
@rprunskas - please rebase from master. Then @anwzhang can re-review.

**Comment by rprunskas** [comment]
@bretg, @anwzhang I have rebased from upstream/master.

**Comment by mjacobsonny** [comment]
@vladasdrejeris -- Thank you for submitting this!  At the moment, we are working on a fairly major overhaul to Prebid Mobile (see: #73 ).  I would recommend that we hold off on this for the immediate term, and we can work with you to ensure that the Adform integration is compatible with Prebid Mobile 1.0.

**Comment by anwzhang** [comment]
Hi @rprunskas, Prebid Mobile 1.0 is released, if you're still interested, can you modify this PR and raise again?

**Comment by bszekely1** [comment]
I am closing this PR since there has been no action taken on this PR in over a year. If you wish to have this project released, please provide an issue ticket first describing the goal, a description with a technical architecture and we will review it on our Mobile PMC.

**Pull request closed without merging**
